import "./globals.css";
import { League_Spartan } from "next/font/google";
import Image from "next/image";
import bgHeader from "../public/images/bg-header-desktop.svg";
import bgHeaderMobile from "../public/images/bg-header-mobile.svg";

const LeagueSpartan = League_Spartan({
  subsets: ["latin"],
  weight: ["500", "700"],
});

export const metadata = {
  title: "Job listings with filtering | Frontend Mentor",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={LeagueSpartan.className}>
        <header className="mb-8 bg-DesaturatedDarkCyan">
          <Image
            src={bgHeader}
            priority
            alt="background-header"
            className=" hidden lg:flex w-full"
          />
          <Image
            src={bgHeaderMobile}
            priority
            alt="background-header"
            className=" flex lg:hidden w-full"
          />
        </header>
        {children}
      </body>
    </html>
  );
}
